### ISSUE TITLE
Wish this would work

### ISSUE THREAD

**Issue by drumWatts** [burhandodhy/wordpress-autocomplete#1]
I'd love to use this package, but it simply won't activate. It installs, but the WP autocomplete just doesn't work. I'm transitioning from Netbeans which has awesome WP autocomplete and think your plugin will do something similar for Atom. I'm using Atom 1.26.0 x64 on a Mac. 

I've tried a million different things: relaunching Atom, installing, uninstalling, deactivating other installed packages (I have many working correctly), etc.

I know this is a vague question, but are there any known incompatibilities or conflicts? Any general troubleshooting advice for this particular package?

**Comment by vitaliy-tkachuk** [comment]
I have same issue, but even worst. After installing this package, when I try to run Atom there are such errors:

Failed to load snippets from '/home/vitfl88/.atom/packages/wordpress-autocomplete/snippets/functions.cson'
/home/vitfl88/.atom/packages/wordpress-autocomplete/snippets/functions.cson: Duplicate key ''

**Comment by R3dRidle** [comment]
I get the exact same error as @VitFL

**Comment by R3dRidle** [comment]
Editing the duplicate keys does get rid of the error. But ATOM just hangs after that. Atom does nothing anymore.

**Comment by burhandodhy** [comment]
I published the update. Please update and let me know

**Comment by edsvcs** [comment]
Confirming that this now works for me. Thank you! Super helpful!
