### ISSUE TITLE
Error: Failed to load snippets from ***/snippets/functions.cson

### ISSUE THREAD

**Issue by vitaliy-tkachuk** [burhandodhy/wordpress-autocomplete#2]
I've just installed this package and it wont work, when I try to run Atom there is such error:

Failed to load snippets from '/home/vitfl88/.atom/packages/wordpress-autocomplete/snippets/functions.cson'
/home/vitfl88/.atom/packages/wordpress-autocomplete/snippets/functions.cson: Duplicate key ''

My Atom version is 1.26.1

![screenshot from 2018-05-02 23-47-31](https://user-images.githubusercontent.com/38079541/39548447-54380316-4e63-11e8-9dbf-0c069652f2e6.png)

**Comment by dave-green-uk** [comment]
The issue is that there are some functions without descriptions, so the keys in the CSON file are empty strings, causing the `Duplicate key ''` issue.

**Comment by burhandodhy** [comment]
Hi Guys,

Its running fine on my Atom.io . I'm going to investigate the issue and will inform you as soon as I get something.

**Comment by davehamer** [comment]
Seems to be due to this:
https://github.com/atom/snippets/pull/250

I've manually gone through and given everything with "" a description, but now there are actual duplicate descriptions... I'm not sure how much more of this I can take! :)

Any updates from your end? Is there something to stop Atom complaining on a duplicate key? It's just a description after all!

A really quick fix would be to replace the descriptions with the 'prefix'. This should make them all unique

**Comment by davehamer** [comment]
A really quick fix - I used a find/replace regex to do this:
`^\t"(.*)":\r\n\t\t"prefix":"(.*)"`
`\t"($2)":\r\n\t\t"prefix":"($2)"`

[functions.cson.zip](https://github.com/burhandodhy/wordpress-autocomplete/files/2000798/functions.cson.zip)

**Comment by R3dRidle** [comment]
With this version of @BristolITDave the error is gone, but Atom just hangs after opening.

![image](https://user-images.githubusercontent.com/13661524/41415841-cf3a8b72-6fe9-11e8-9197-df6efa92bf91.png)

**Comment by BiswasSuman** [comment]
**In my atom v1.26.1, I have the same problem.**

**Comment by StinkyPig** [comment]
Same problem here, I'd love this package to work.

**Comment by burhandodhy** [comment]
I published the update. Please update and let me know

**Comment by davehamer** [comment]
Just done a really quick test - Uninstalled and reinstalled from repo, ALL WORKS!

Thank you so much 👍

**Comment by BiswasSuman** [comment]
Thank you so much.
Tested it. Now working fine.
